# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5579e41a3ad198fdee31fcb59a4dea18ab13e3d25bc12756f69c792a40d8d7d822cd142d0cfc60afa05f856d7ef9d0679537cebd78438312a2b3a1cda76fa0aa

test:
  secret_key_base: ab32cb9c397c9f982a21f1deb3b6d23e884e1f78665e7fabab86a1427cd23f278781680e6c7eb4a0d5eb1ea8a74dcf7b4b67700a1b9112702678ba2881037983

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
