User.create!(login_id: "testuser1", password: "foobar")
User.create!(login_id: "testuser2", password: "foobar")
User.create!(login_id: "testuser3", password: "foobar")
Group.create!()
Group.create!()
Member.create!(user_id:1, group_id:1)
Member.create!(user_id:2, group_id:2)
Member.create!(user_id:3, group_id:1)
Chat.create!(text:"あのイーハトーヴォの透き通ったアレ", user_id:1, group_id:1)
Chat.create!(text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit....", user_id:2, group_id:1)
